name: RIGD-LOXIA
favicon: null
layout_spectrum: 0.00626
typography_spectrum: 0.6947363875806332
title: RIGD LOXIA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.22872465732507408
  lightness: 0.9043691258411855
  saturation: 0.6360437034163624
  rhythmicContrast: 0.9076430140994489
purpose: []
